import { chromium } from '@playwright/test';
import { spawn } from 'node:child_process';
import fs from 'node:fs/promises';

const server = spawn('npm', ['run', 'dev'], { env: { ...process.env, AGENT_IC_DEMO_MODE: 'true', NEXT_PUBLIC_AGENT_IC_RECORDING: 'true' }, stdio: 'inherit', shell: true });
await new Promise(r => setTimeout(r, 4000));
const browser = await chromium.launch({ headless: true });
const context = await browser.newContext({ viewport: { width: 1920, height: 1080 } });
const page = await context.newPage();
await page.goto('http://127.0.0.1:3000/submit?recording=1', { waitUntil: 'networkidle' });
await page.screenshot({ path: 'debug-before.png' });
await page.getByTestId('run-capital-experiment').click();
await new Promise(r => setTimeout(r, 6000));
await page.screenshot({ path: 'debug-after.png' });
const html = await page.content();
await fs.writeFile('debug.html', html.slice(0, 30000));
await context.close();
await browser.close();
server.kill('SIGTERM');
console.log('done');
